### ISSUE TITLE
Unknown auth request for blob.cat

### ISSUE THREAD

**Issue by hdhoang** [mihaip/streamspigot#1]
hello, thanks for making this

i'm trying out https://streamspigot.com/masto-feeder/ for a blob.cat account, however when redirecting spigot `sign-in-callback`, there's only a message:

```
Input error: Unknown auth request 
```

And blob.cat settings page shows no OAuth token for spigot.

I have tried several browsers as well as private modes. Could you take a look when you have energy? thanks

in blob.cat they say the Backend version is [3.3.1-0-gbba467b39-blob](https://akkoma.dev/AkkomaGang/akkoma/commit/bba467b39)

**Comment by mihaip** [comment]
I've only tested the Masto Feeder tool with Mastodon 4.x. blob.cat appears to be running Akkoma, which is Mastodon-compatible, but I guess there's a difference in the auth path. Nothing jumps out at https://docs.akkoma.dev/stable/development/API/differences_in_mastoapi_responses/#authentication, but I won't have time to investigate further in the near future.

**Comment by hdhoang** [comment]
sorry to hijack the issue. I made another account on mas.to recently, and could make a feed.

However, for some weeks now, I cannot authenticate masto-feeder with mas.to again. I tried deleting the authorization in my account, but issue persists. After receiving credentials, mas.to shows error page with:

> Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

and url is `https://mas.to/oauth/authorize?client_id=9dKuWOdL2IFuQU2n...snip...4CF-LKg-Ec&response_type=code&redirect_uri=https%3A%2F%2Fwww.streamspigot.com%2Fmasto-feeder%2Fsign-in-callback&scope=read%3Aaccounts+read%3Afollows+read%3Alists+read%3Astatuses&force_login=false&state=85353688....snip...d56817b7`.

Perhaps this is relevant https://github.com/mastodon/mastodon/issues/27740

mas.to has been running 4.2.8 since feb https://mas.to/@trumpet/111981287043677366, and my account is from end of 2024-04.

Could you try reregistering oauth app for this instance somehow? thanks

**Comment by mihaip** [comment]
@hdhoang I think I fixed it, can you try again?

Background: API clients like StreamSpigot need to register with each instance, and I maintain a map of that registration keyed by instance URL. I recently added some normalization/cleanup of those URLs (https://github.com/mihaip/streamspigot/commit/fc86d8555d4593b8ca1bb548d875fce4c3d7b9a5) and the existing mas.to registration was keyed `https://mas.to/` (with the trailing slash). Post-normalization the slash was dropped, and StreamSpigot tried to register a new app, but that made things not match. I cleaned up the data.

**Comment by hdhoang** [comment]
I tried again just now and could generate a feed, thanks!

Just an extra note for anyone else, when I submitted literally `HTTPS://mas.to` (capitals as written by swiping keyboard) to spigot, mas.to says:

> The redirect uri included is not valid. 

But I was successful with key url `https://mas.to/`.

**Comment by hdhoang** [comment]
er, I tried with blob cat and spigot works too. great work!
