### ISSUE TITLE
Masto Feeder Topic Link back to the home Instance

### ISSUE THREAD

**Issue by lairsdragon** [mihaip/streamspigot#2]
Hi!

The Feed for Mastodon works quite fine, what I am missing is a link back to the topic on my home server to reply,fav or boost the topic.
Did I (or my feed Reader) miss it?

Thanks for this nice piece of Software

cheerio
steve

**Comment by mihaip** [comment]
There is now a "Use Local URLs" preference that you can configure to do this:

![Screenshot 2024-05-02 at 23 41 32@2x](https://github.com/mihaip/streamspigot/assets/513813/76c6d20d-1f73-4bd7-83f1-bd26e3371167)
